const cases={
external:{letter:'A',title:'Um terceiro impede a execução',event:'Um terceiro intervém',sub:'A queria prosseguir; é impedido.',facts:'Um terceiro contém A durante a execução. A ainda queria prosseguir, mas a intervenção impede a morte de B.',note:'a interrupção<br>vem de fora ↗',law:'Art. 14, II',classification:'Tentativa',reason:'A execução começou, mas o crime não se consumou por circunstância alheia à vontade de A.',consequence:'Salvo disposição em contrário, pena do crime consumado reduzida de um a dois terços. A fração exige fundamentação.',foot:'não consumou ≠ não responde',color:'coral',graphic:'<path class="cut" d="M446 70l-33 110m47-99-34 110"/><path d="M391 81q22-32 37 0m-27-17 0-15m14 14 5-16"/>'},
stop:{letter:'B',title:'A interrompe voluntariamente a execução',event:'A decide não prosseguir',sub:'Ainda podia continuar a execução.',facts:'Durante a execução, A abandona definitivamente este empreendimento, embora ainda pudesse prosseguir. Nesta hipótese, interromper os atos basta para que a morte não ocorra.',note:'podia continuar;<br>decidiu parar.',law:'Art. 15',classification:'Desistência voluntária',reason:'A abandona voluntariamente a execução antes de completar os atos necessários à produção do resultado.',consequence:'Responde apenas pelos atos já praticados que configurem delito.',foot:'parar a execução',color:'yellow',graphic:'<path d="M405 145v-40q0-10 7-8l4 29V81q0-12 8-8l3 51V74q2-12 9-5l2 56 3-43q4-9 9-1l-2 55 13-20q10-5 10 5l-20 45-28 7z"/><path d="M394 175q32 18 64-1"/>'},
rescue:{letter:'C',title:'A intervém e impede eficazmente a morte',event:'A neutraliza o curso',sub:'Sua intervenção evita a morte.',facts:'Depois de administrar veneno, A fornece antídoto e impede efetivamente a morte de B. Sua intervenção é causalmente relevante: B não havia sido salvo por terceiro.',note:'não basta se arrepender:<br>é preciso impedir.',law:'Art. 15',classification:'Arrependimento eficaz',reason:'Os atos capazes de produzir o resultado já ocorreram. A age sobre o curso causal e impede sua produção.',consequence:'Responde apenas pelos atos já praticados que configurem delito.',foot:'impedir o resultado',color:'green',graphic:'<path d="M412 83h31v19l11 18v57h-51v-57l9-18z M409 84h38 M416 74h23v9 M404 132h49"/><path d="M423 142v24m-10-12h23"/>'}
};
const byId=id=>document.getElementById(id);
const originalAction=byId("starting-action").innerHTML;
document.querySelectorAll('[data-case]').forEach(button=>button.addEventListener('click',()=>{
 const key=button.dataset.case,c=cases[key];document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));
 document.querySelector('.drawing-paper').dataset.state=key;
 byId('starting-action').innerHTML=key==='rescue'?'<path d="M101 76h25v18l9 12v66H92v-66l9-12z M97 76h33 M94 127h39 M160 135h32l-6 40h-20z M145 111l12 15"/><text x="96" y="153" style="font-size:12px">×</text>':originalAction;
 byId('case-letter').textContent=c.letter;byId('drawing-title').textContent=c.title;byId('drawing-desc').textContent=c.facts+' '+c.reason;
 byId('event-graphic').innerHTML=c.graphic+'<text x="364" y="258" id="event-label"></text><text class="small" x="364" y="282" id="event-sub"></text>';
 byId('event-label').textContent=c.event;byId('event-sub').textContent=c.sub;
 byId('case-facts').textContent=c.facts;byId('hand-note').innerHTML=c.note;byId('law-label').textContent=c.law;byId('classification').textContent=c.classification;byId('reason').textContent=c.reason;byId('consequence').textContent=c.consequence;byId('finding-note').textContent=c.foot;byId('finding').className='finding '+c.color;
}));
